-- Run this once in a Snowflake worksheet with a role that can create warehouses,
-- databases, and roles. Names match the defaults in .env.example.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS SMART_AI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS SMART_AI_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SMART_AI_ANALYTICS.ECOMMERCE;

USE WAREHOUSE SMART_AI_WH;
USE DATABASE SMART_AI_ANALYTICS;
USE SCHEMA ECOMMERCE;

CREATE FILE FORMAT IF NOT EXISTS SMART_AI_CSV
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORYID NUMBER(38, 0) NOT NULL,
    CATEGORYNAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR,
    PICTURE VARCHAR,
    PRIMARY KEY (CATEGORYID)
);

CREATE TABLE IF NOT EXISTS SUPPLIERS (
    SUPPLIERID NUMBER(38, 0) NOT NULL,
    COMPANYNAME VARCHAR NOT NULL,
    CONTACTNAME VARCHAR,
    CONTACTTITLE VARCHAR,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    REGION VARCHAR,
    POSTALCODE VARCHAR,
    COUNTRY VARCHAR,
    PHONE VARCHAR,
    FAX VARCHAR,
    HOMEPAGE VARCHAR,
    PRIMARY KEY (SUPPLIERID)
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCTID NUMBER(38, 0) NOT NULL,
    PRODUCTNAME VARCHAR NOT NULL,
    SUPPLIERID NUMBER(38, 0),
    CATEGORYID NUMBER(38, 0),
    QUANTITYPERUNIT VARCHAR,
    UNITPRICE NUMBER(18, 2),
    UNITSINSTOCK NUMBER(38, 0),
    UNITSONORDER NUMBER(38, 0),
    REORDERLEVEL NUMBER(38, 0),
    DISCONTINUED NUMBER(1, 0),
    PRIMARY KEY (PRODUCTID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDERID NUMBER(38, 0) NOT NULL,
    CUSTOMERID VARCHAR,
    EMPLOYEEID NUMBER(38, 0),
    ORDERDATE TIMESTAMP_NTZ,
    REQUIREDDATE TIMESTAMP_NTZ,
    SHIPPEDDATE TIMESTAMP_NTZ,
    SHIPVIA NUMBER(38, 0),
    FREIGHT NUMBER(18, 2),
    SHIPNAME VARCHAR,
    SHIPADDRESS VARCHAR,
    SHIPCITY VARCHAR,
    SHIPREGION VARCHAR,
    SHIPPOSTALCODE VARCHAR,
    SHIPCOUNTRY VARCHAR,
    PRIMARY KEY (ORDERID)
);

CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDERID NUMBER(38, 0) NOT NULL,
    PRODUCTID NUMBER(38, 0) NOT NULL,
    UNITPRICE NUMBER(18, 2) NOT NULL,
    QUANTITY NUMBER(38, 0) NOT NULL,
    DISCOUNT NUMBER(10, 4) NOT NULL,
    PRIMARY KEY (ORDERID, PRODUCTID)
);

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS SMART_AI_ANALYST;
GRANT USAGE ON WAREHOUSE SMART_AI_WH TO ROLE SMART_AI_ANALYST;
GRANT USAGE ON DATABASE SMART_AI_ANALYTICS TO ROLE SMART_AI_ANALYST;
GRANT USAGE ON SCHEMA SMART_AI_ANALYTICS.ECOMMERCE TO ROLE SMART_AI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SMART_AI_ANALYTICS.ECOMMERCE
    TO ROLE SMART_AI_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SMART_AI_ANALYTICS.ECOMMERCE
    TO ROLE SMART_AI_ANALYST;

-- Replace YOUR_USER with the Snowflake user used by this application.
-- GRANT ROLE SMART_AI_ANALYST TO USER YOUR_USER;
