-- Run manually in an authorized administrator worksheet.
-- The preparation CLI creates a local copy with the separate loader public key.
-- No privileges are granted to SMART_AI_APP or SMART_AI_ANALYST.
USE ROLE SYSADMIN;
CREATE STAGE IF NOT EXISTS SMART_AI_ANALYTICS.ECOMMERCE.SMART_AI_LOAD_STAGE;

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS SMART_AI_LOADER;
GRANT USAGE ON WAREHOUSE SMART_AI_WH TO ROLE SMART_AI_LOADER;
GRANT USAGE ON DATABASE SMART_AI_ANALYTICS TO ROLE SMART_AI_LOADER;
GRANT USAGE ON SCHEMA SMART_AI_ANALYTICS.ECOMMERCE TO ROLE SMART_AI_LOADER;
GRANT USAGE ON FILE FORMAT SMART_AI_ANALYTICS.ECOMMERCE.SMART_AI_CSV TO ROLE SMART_AI_LOADER;
GRANT READ ON STAGE SMART_AI_ANALYTICS.ECOMMERCE.SMART_AI_LOAD_STAGE TO ROLE SMART_AI_LOADER;
GRANT WRITE ON STAGE SMART_AI_ANALYTICS.ECOMMERCE.SMART_AI_LOAD_STAGE TO ROLE SMART_AI_LOADER;
GRANT SELECT, INSERT ON TABLE SMART_AI_ANALYTICS.ECOMMERCE.CATEGORIES TO ROLE SMART_AI_LOADER;
GRANT SELECT, INSERT ON TABLE SMART_AI_ANALYTICS.ECOMMERCE.SUPPLIERS TO ROLE SMART_AI_LOADER;
GRANT SELECT, INSERT ON TABLE SMART_AI_ANALYTICS.ECOMMERCE.PRODUCTS TO ROLE SMART_AI_LOADER;
GRANT SELECT, INSERT ON TABLE SMART_AI_ANALYTICS.ECOMMERCE.ORDERS TO ROLE SMART_AI_LOADER;
GRANT SELECT, INSERT ON TABLE SMART_AI_ANALYTICS.ECOMMERCE.ORDER_DETAILS TO ROLE SMART_AI_LOADER;

-- If the user already exists, stop and inspect it; never use OR REPLACE.
CREATE USER SMART_AI_LOADER_APP
    TYPE = SERVICE
    RSA_PUBLIC_KEY = 'PASTE_LOADER_PUBLIC_KEY_HERE'
    DEFAULT_ROLE = SMART_AI_LOADER
    DEFAULT_SECONDARY_ROLES = ()
    DEFAULT_WAREHOUSE = SMART_AI_WH
    COMMENT = 'Dedicated loading identity for five analytics source tables';
GRANT ROLE SMART_AI_LOADER TO USER SMART_AI_LOADER_APP;

SHOW GRANTS TO USER SMART_AI_LOADER_APP;
